name: Plugin builder and release

on:
  pull_request:
    branches: [ "main" ]
  release:
    types:
      - created
  workflow_dispatch:

env:
  PROJECT_PATH: "SimpleTags.csproj"
  PROJECT_NAME: "SimpleTags"
  OUTPUT_PATH: "./SimpleTags"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -o ${{ env.OUTPUT_PATH }}

      - name: Create release asset
        if: github.event_name == 'release'
        run: |
          cd ${{ env.OUTPUT_PATH }}
          zip -r ../${{ env.PROJECT_NAME }}-${{ github.event.release.tag_name }}.zip .

      - name: Upload release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./${{ env.PROJECT_NAME }}-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}